---
linters:
  ErbSafety:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: true
      Layout/LineLength:
        Max: 120
      Layout/TrailingEmptyLines:
        Enabled: true
  RightTrim:
    enabled: true
    enforced_style: '-'
  SpaceAroundErbTag:
    enabled: true
  HardCodedString:
    enabled: true
  SpaceInHtmlTag:
    enabled: true
