# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Style/TrailingCommaInHashLiteral:
  Enabled: true
Style/EmptyMethod:
  Enabled: true
  EnforcedStyle: expanded
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/MethodLength:
  Enabled: true
  Max: 25
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - db/**/*.rb
Style/SpecialGlobalVars:
  Exclude:
    - bin/*
    - script/*
Metrics/CyclomaticComplexity:
  Exclude:
    - bin/*
    - script/*
Metrics/PerceivedComplexity:
  Exclude:
    - bin/*
    - script/*
Style/GlobalStdStream:
  Exclude:
    - bin/*
    - script/*
Layout/LineLength:
  Max: 120
